### ISSUE TITLE
why do u use R2DBC 

### ISSUE THREAD

**Issue by fizz12344321** [owahlen/task-manager#26]
Hi, i am reading your project and i am interested in this, but i have a question, why do you use R2DBC instead of other non blocking IO like Hibernate Reactive or others... can you tell me your purpose, the pros and cons of R2DBC, thank you so much

**Comment by owahlen** [comment]
Hello Fizz,
actually, Hibernate Reactive is an Object Mapper. The underlying DB client is Vert.x. Spring Data is a more simple way to map relational tables to objects. VMWare provides an official repository to use R2DBC as DB client. This is why R2DBC was chosen for Spring Data.
So you may ask why Spring Data was chosen over Hibernate:
Spring Data is simpler and faster. For most project it is sufficient. Also from my experience in more complex ER models and transaction scopes Hibernate often tends to become more difficult to manage and inefficient. The inefficiency comes from more complex and sometimes redundant queries that hibernate is creating.
If you have not yet taken a decision on how do your object mapping, I also recommend to take a look at jooq. They however also rely on R2DBC.
